#-----------------------------
# 数据配置
#-----------------------------
data:
  # --- 数据源控制 ---
  use_file_dataset: true   # 设置为 true 使用下面的 data_path, 设置为 false 则动态生成模拟数据
  data_path: "./data/semi_realistic_dataset.npz" 
  
  # --- 通用数据参数 ---
  num_nodes: 207           
  num_features: 1          
  num_timesteps_input: 12  
  num_timesteps_output: 12

#-----------------------------
# 模型配置
#-----------------------------
model:
  spatial_channels: 16
  out_channels: 64
  time_kernel_size: 3
  graph_kernel_size: 1

#-----------------------------
# 训练配置
#-----------------------------
training:
  device: "cuda"
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  optimizer: "adam"
  
#-----------------------------
# 断点续传与日志配置
#-----------------------------
checkpoint:
  save_dir: "./checkpoints"
  save_every_epochs: 5
  load_checkpoint: True